      { @selector( MulleObjCArchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c636b4d;MulleObjCArchiver;;
      { @selector( MulleObjCArrayReverseEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 1f04617c;MulleObjCArrayReverseEnumerator;;
      { @selector( MulleObjCBufferedInputStream), MULLE_OBJC_NO_CATEGORYID },      // 0d289418;MulleObjCBufferedInputStream;;
      { @selector( MulleObjCBufferedOutputStream), MULLE_OBJC_NO_CATEGORYID },      // f919266f;MulleObjCBufferedOutputStream;;
      { @selector( MulleObjCContainer), @selector( NSArray) },      // 6380327d;MulleObjCContainer;233490fe;NSArray
      { @selector( MulleObjCContainer), MULLE_OBJC_NO_CATEGORYID },      // 6380327d;MulleObjCContainer;;
      { @selector( MulleObjCInMemoryInputStream), MULLE_OBJC_NO_CATEGORYID },      // c11e0f43;MulleObjCInMemoryInputStream;;
      { @selector( MulleObjCOutputStream), MULLE_OBJC_NO_CATEGORYID },      // 94c18dd3;MulleObjCOutputStream;;
      { @selector( MulleObjCPropertyListPrinting), MULLE_OBJC_NO_CATEGORYID },      // ae35af0f;MulleObjCPropertyListPrinting;;
      { @selector( MulleObjCUTF8StreamReader), MULLE_OBJC_NO_CATEGORYID },      // 1570378d;MulleObjCUTF8StreamReader;;
      { @selector( MulleObjCUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c32efb0;MulleObjCUnarchiver;;
      { @selector( MulleObjCUnkeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // f57df630;MulleObjCUnkeyedArchiver;;
      { @selector( MulleObjCUnkeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b124a0f;MulleObjCUnkeyedUnarchiver;;
      { @selector( NSArchiver), @selector( OSBase) },      // 2a2e712f;NSArchiver;b8ece9a7;OSBase
      { @selector( NSArchiver), MULLE_OBJC_NO_CATEGORYID },      // 2a2e712f;NSArchiver;;
      { @selector( NSArray), @selector( DataComponents) },      // 233490fe;NSArray;486bf892;DataComponents
      { @selector( NSArray), @selector( MulleMutableArrayAdditions) },      // 233490fe;NSArray;06c6446f;MulleMutableArrayAdditions
      { @selector( NSArray), @selector( MulleObjCKVCArithmetic) },      // 233490fe;NSArray;51efafe9;MulleObjCKVCArithmetic
      { @selector( NSArray), @selector( NSCoder) },      // 233490fe;NSArray;100c54ba;NSCoder
      { @selector( NSArray), @selector( NSEnumerator) },      // 233490fe;NSArray;e631d30d;NSEnumerator
      { @selector( NSArray), @selector( NSLocale) },      // 233490fe;NSArray;22b7d78c;NSLocale
      { @selector( NSArray), @selector( NSPropertyListParsing) },      // 233490fe;NSArray;060a8c9c;NSPropertyListParsing
      { @selector( NSArray), @selector( NSSortDescriptor) },      // 233490fe;NSArray;38a79ab2;NSSortDescriptor
      { @selector( NSArray), @selector( NSString) },      // 233490fe;NSArray;1994a171;NSString
      { @selector( NSArray), @selector( PropertyListPrinting) },      // 233490fe;NSArray;91aeee11;PropertyListPrinting
      { @selector( NSArray), @selector( StringComponents) },      // 233490fe;NSArray;6e3b19c0;StringComponents
      { @selector( NSArray), @selector( _KeyValueCoding) },      // 233490fe;NSArray;c60e3006;_KeyValueCoding
      { @selector( NSArray), MULLE_OBJC_NO_CATEGORYID },      // 233490fe;NSArray;;
      { @selector( NSAssertionHandler), MULLE_OBJC_NO_CATEGORYID },      // a1951b2b;NSAssertionHandler;;
      { @selector( NSCalendarDate), @selector( NSDateFormatter) },      // b8742fcb;NSCalendarDate;6d2cd542;NSDateFormatter
      { @selector( NSCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // b8742fcb;NSCalendarDate;;
      { @selector( NSCharacterSet), @selector( MulleObjCUnicode) },      // bb258d72;NSCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // bb258d72;NSCharacterSet;;
      { @selector( NSCoder), MULLE_OBJC_NO_CATEGORYID },      // 100c54ba;NSCoder;;
      { @selector( NSCondition), @selector( NSDate) },      // 0397143e;NSCondition;cfcedd21;NSDate
      { @selector( NSConditionLock), @selector( NSDate) },      // 5e0deecf;NSConditionLock;cfcedd21;NSDate
      { @selector( NSConstantString), MULLE_OBJC_NO_CATEGORYID },      // 02cf74f7;NSConstantString;;
      { @selector( NSData), @selector( Components) },      // 8fce7861;NSData;c6c03895;Components
      { @selector( NSData), @selector( NSCoder) },      // 8fce7861;NSData;100c54ba;NSCoder
      { @selector( NSData), @selector( NSPropertyListParsing) },      // 8fce7861;NSData;060a8c9c;NSPropertyListParsing
      { @selector( NSData), @selector( NSString) },      // 8fce7861;NSData;1994a171;NSString
      { @selector( NSData), @selector( PropertyListPrinting) },      // 8fce7861;NSData;91aeee11;PropertyListPrinting
      { @selector( NSData), @selector( _Unicode) },      // 8fce7861;NSData;ac921392;_Unicode
      { @selector( NSData), MULLE_OBJC_NO_CATEGORYID },      // 8fce7861;NSData;;
      { @selector( NSDate), @selector( NSCalendarDate) },      // cfcedd21;NSDate;b8742fcb;NSCalendarDate
      { @selector( NSDate), @selector( NSCoder) },      // cfcedd21;NSDate;100c54ba;NSCoder
      { @selector( NSDate), @selector( NSDateFormatter) },      // cfcedd21;NSDate;6d2cd542;NSDateFormatter
      { @selector( NSDate), @selector( PropertyListPrinting) },      // cfcedd21;NSDate;91aeee11;PropertyListPrinting
      { @selector( NSDate), MULLE_OBJC_NO_CATEGORYID },      // cfcedd21;NSDate;;
      { @selector( NSDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 6d2cd542;NSDateFormatter;;
      { @selector( NSDictionary), @selector( NSArray) },      // 8b2abcad;NSDictionary;233490fe;NSArray
      { @selector( NSDictionary), @selector( NSCoder) },      // 8b2abcad;NSDictionary;100c54ba;NSCoder
      { @selector( NSDictionary), @selector( NSEnumerator) },      // 8b2abcad;NSDictionary;e631d30d;NSEnumerator
      { @selector( NSDictionary), @selector( NSLocale) },      // 8b2abcad;NSDictionary;22b7d78c;NSLocale
      { @selector( NSDictionary), @selector( NSMutableDictionary) },      // 8b2abcad;NSDictionary;2f2fa84a;NSMutableDictionary
      { @selector( NSDictionary), @selector( NSPropertyListParsing) },      // 8b2abcad;NSDictionary;060a8c9c;NSPropertyListParsing
      { @selector( NSDictionary), @selector( NSString) },      // 8b2abcad;NSDictionary;1994a171;NSString
      { @selector( NSDictionary), @selector( PropertyList) },      // 8b2abcad;NSDictionary;827edd0f;PropertyList
      { @selector( NSDictionary), @selector( PropertyListPrinting) },      // 8b2abcad;NSDictionary;91aeee11;PropertyListPrinting
      { @selector( NSDictionary), @selector( _KeyValueCoding) },      // 8b2abcad;NSDictionary;c60e3006;_KeyValueCoding
      { @selector( NSDictionary), MULLE_OBJC_NO_CATEGORYID },      // 8b2abcad;NSDictionary;;
      { @selector( NSEnumerator), @selector( NSArray) },      // e631d30d;NSEnumerator;233490fe;NSArray
      { @selector( NSEnumerator), MULLE_OBJC_NO_CATEGORYID },      // e631d30d;NSEnumerator;;
      { @selector( NSError), @selector( String) },      // 17836f0e;NSError;04f48586;String
      { @selector( NSError), MULLE_OBJC_NO_CATEGORYID },      // 17836f0e;NSError;;
      { @selector( NSException), @selector( String) },      // 332ec6f9;NSException;04f48586;String
      { @selector( NSException), MULLE_OBJC_NO_CATEGORYID },      // 332ec6f9;NSException;;
      { @selector( NSFormatter), MULLE_OBJC_NO_CATEGORYID },      // d5e6770e;NSFormatter;;
      { @selector( NSKeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 8a2c6980;NSKeyedArchiver;;
      { @selector( NSKeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // ea42e9ff;NSKeyedUnarchiver;;
      { @selector( NSLocale), MULLE_OBJC_NO_CATEGORYID },      // 22b7d78c;NSLocale;;
      { @selector( NSLock), @selector( NSDate) },      // cd92d31f;NSLock;cfcedd21;NSDate
      { @selector( NSMethodSignature), @selector( NSString) },      // 523989f9;NSMethodSignature;1994a171;NSString
      { @selector( NSMutableArray), @selector( NSCoder) },      // f5e6dbdd;NSMutableArray;100c54ba;NSCoder
      { @selector( NSMutableArray), @selector( NSSet) },      // f5e6dbdd;NSMutableArray;9f69e3e4;NSSet
      { @selector( NSMutableArray), @selector( NSSortDescriptor) },      // f5e6dbdd;NSMutableArray;38a79ab2;NSSortDescriptor
      { @selector( NSMutableArray), @selector( _KeyValueCoding) },      // f5e6dbdd;NSMutableArray;c60e3006;_KeyValueCoding
      { @selector( NSMutableArray), MULLE_OBJC_NO_CATEGORYID },      // f5e6dbdd;NSMutableArray;;
      { @selector( NSMutableCharacterSet), @selector( MulleObjCUnicode) },      // a5cef654;NSMutableCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSMutableCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // a5cef654;NSMutableCharacterSet;;
      { @selector( NSMutableData), @selector( MulleObjCOutputStream) },      // 5d7fdc81;NSMutableData;94c18dd3;MulleObjCOutputStream
      { @selector( NSMutableData), @selector( NSCoder) },      // 5d7fdc81;NSMutableData;100c54ba;NSCoder
      { @selector( NSMutableData), @selector( NSString) },      // 5d7fdc81;NSMutableData;1994a171;NSString
      { @selector( NSMutableData), @selector( Unicode) },      // 5d7fdc81;NSMutableData;94ece403;Unicode
      { @selector( NSMutableData), MULLE_OBJC_NO_CATEGORYID },      // 5d7fdc81;NSMutableData;;
      { @selector( NSMutableDictionary), @selector( NSArray) },      // 2f2fa84a;NSMutableDictionary;233490fe;NSArray
      { @selector( NSMutableDictionary), @selector( NSCoder) },      // 2f2fa84a;NSMutableDictionary;100c54ba;NSCoder
      { @selector( NSMutableDictionary), @selector( _KeyValueCoding) },      // 2f2fa84a;NSMutableDictionary;c60e3006;_KeyValueCoding
      { @selector( NSMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2f2fa84a;NSMutableDictionary;;
      { @selector( NSMutableSet), @selector( NSArray) },      // 1fa72100;NSMutableSet;233490fe;NSArray
      { @selector( NSMutableSet), @selector( NSCoder) },      // 1fa72100;NSMutableSet;100c54ba;NSCoder
      { @selector( NSMutableSet), MULLE_OBJC_NO_CATEGORYID },      // 1fa72100;NSMutableSet;;
      { @selector( NSMutableString), @selector( NSData) },      // 63662493;NSMutableString;8fce7861;NSData
      { @selector( NSMutableString), @selector( Search) },      // 63662493;NSMutableString;646a2c9c;Search
      { @selector( NSMutableString), MULLE_OBJC_NO_CATEGORYID },      // 63662493;NSMutableString;;
      { @selector( NSNotification), MULLE_OBJC_NO_CATEGORYID },      // 4cf6fadb;NSNotification;;
      { @selector( NSNotificationCenter), MULLE_OBJC_NO_CATEGORYID },      // 1c4865c0;NSNotificationCenter;;
      { @selector( NSNull), @selector( NSString) },      // f0c42d79;NSNull;1994a171;NSString
      { @selector( NSNull), @selector( PropertyListPrinting) },      // f0c42d79;NSNull;91aeee11;PropertyListPrinting
      { @selector( NSNumber), @selector( Math) },      // 8ba34f39;NSNumber;569c3af5;Math
      { @selector( NSNumber), @selector( MulleObjCKVCArithmetic) },      // 8ba34f39;NSNumber;51efafe9;MulleObjCKVCArithmetic
      { @selector( NSNumber), @selector( NSCoder) },      // 8ba34f39;NSNumber;100c54ba;NSCoder
      { @selector( NSNumber), @selector( NSLocale) },      // 8ba34f39;NSNumber;22b7d78c;NSLocale
      { @selector( NSNumber), @selector( NSString) },      // 8ba34f39;NSNumber;1994a171;NSString
      { @selector( NSNumber), @selector( PropertyListPrinting) },      // 8ba34f39;NSNumber;91aeee11;PropertyListPrinting
      { @selector( NSNumber), MULLE_OBJC_NO_CATEGORYID },      // 8ba34f39;NSNumber;;
      { @selector( NSNumberFormatter), MULLE_OBJC_NO_CATEGORYID },      // 60a672fc;NSNumberFormatter;;
      { @selector( NSObject), @selector( KVCSupport) },      // b3a66256;NSObject;5d846183;KVCSupport
      { @selector( NSObject), @selector( MulleCompareDescription) },      // b3a66256;NSObject;9df35a1c;MulleCompareDescription
      { @selector( NSObject), @selector( NSCoder) },      // b3a66256;NSObject;100c54ba;NSCoder
      { @selector( NSObject), @selector( NSPropertyListParsing) },      // b3a66256;NSObject;060a8c9c;NSPropertyListParsing
      { @selector( NSObject), @selector( NSString) },      // b3a66256;NSObject;1994a171;NSString
      { @selector( NSObject), @selector( _KeyValueCoding) },      // b3a66256;NSObject;c60e3006;_KeyValueCoding
      { @selector( NSObject), @selector( _KeyValueCodingCompatibility) },      // b3a66256;NSObject;a0853a05;_KeyValueCodingCompatibility
      { @selector( NSObject), @selector( _MulleObjCKVCInformation) },      // b3a66256;NSObject;9789c697;_MulleObjCKVCInformation
      { @selector( NSObject), @selector( _NSArray) },      // b3a66256;NSObject;0beba328;_NSArray
      { @selector( NSObject), @selector( _NSCalendarDate) },      // b3a66256;NSObject;83e2187c;_NSCalendarDate
      { @selector( NSObject), @selector( _NSData) },      // b3a66256;NSObject;7f24339e;_NSData
      { @selector( NSObject), @selector( _NSDate) },      // b3a66256;NSObject;bf24985e;_NSDate
      { @selector( NSObject), @selector( _NSDictionary) },      // b3a66256;NSObject;413cd390;_NSDictionary
      { @selector( NSObject), @selector( _NSLocale) },      // b3a66256;NSObject;973379b2;_NSLocale
      { @selector( NSObject), @selector( _NSMutableArray) },      // b3a66256;NSObject;2f8adfe0;_NSMutableArray
      { @selector( NSObject), @selector( _NSMutableData) },      // b3a66256;NSObject;1a3fbdd6;_NSMutableData
      { @selector( NSObject), @selector( _NSMutableDictionary) },      // b3a66256;NSObject;1f96dfdd;_NSMutableDictionary
      { @selector( NSObject), @selector( _NSMutableString) },      // b3a66256;NSObject;7bd64f0d;_NSMutableString
      { @selector( NSObject), @selector( _NSNumber) },      // b3a66256;NSObject;9343014d;_NSNumber
      { @selector( NSObject), @selector( _NSSet) },      // b3a66256;NSObject;2f766bf1;_NSSet
      { @selector( NSObject), @selector( _NSString) },      // b3a66256;NSObject;37e49041;_NSString
      { @selector( NSObject), @selector( _NSTimeZone) },      // b3a66256;NSObject;f3165c68;_NSTimeZone
      { @selector( NSObject), @selector( _NSValue) },      // b3a66256;NSObject;8fc3f568;_NSValue
      { @selector( NSPropertyListSerialization), MULLE_OBJC_NO_CATEGORYID },      // 87901b51;NSPropertyListSerialization;;
      { @selector( NSProxy), @selector( _MulleObjCKVCInformation) },      // 9a42ec29;NSProxy;9789c697;_MulleObjCKVCInformation
      { @selector( NSScanner), @selector( NSLocale) },      // 0b3d6aca;NSScanner;22b7d78c;NSLocale
      { @selector( NSScanner), MULLE_OBJC_NO_CATEGORYID },      // 0b3d6aca;NSScanner;;
      { @selector( NSSet), @selector( NSArray) },      // 9f69e3e4;NSSet;233490fe;NSArray
      { @selector( NSSet), @selector( NSCoder) },      // 9f69e3e4;NSSet;100c54ba;NSCoder
      { @selector( NSSet), @selector( NSString) },      // 9f69e3e4;NSSet;1994a171;NSString
      { @selector( NSSet), @selector( _KeyValueCoding) },      // 9f69e3e4;NSSet;c60e3006;_KeyValueCoding
      { @selector( NSSet), MULLE_OBJC_NO_CATEGORYID },      // 9f69e3e4;NSSet;;
      { @selector( NSSortDescriptor), @selector( NSCoder) },      // 38a79ab2;NSSortDescriptor;100c54ba;NSCoder
      { @selector( NSSortDescriptor), @selector( NSKeyValueCoding) },      // 38a79ab2;NSSortDescriptor;19d06181;NSKeyValueCoding
      { @selector( NSSortDescriptor), MULLE_OBJC_NO_CATEGORYID },      // 38a79ab2;NSSortDescriptor;;
      { @selector( NSString), @selector( ClassCluster) },      // 1994a171;NSString;d38b16ff;ClassCluster
      { @selector( NSString), @selector( Components) },      // 1994a171;NSString;c6c03895;Components
      { @selector( NSString), @selector( DoubleQuotedString) },      // 1994a171;NSString;4cfd171d;DoubleQuotedString
      { @selector( NSString), @selector( Enumerator) },      // 1994a171;NSString;bd761fff;Enumerator
      { @selector( NSString), @selector( Escaping) },      // 1994a171;NSString;742c5512;Escaping
      { @selector( NSString), @selector( Locale) },      // 1994a171;NSString;d6e5bb7d;Locale
      { @selector( NSString), @selector( MulleObjCOutputStream) },      // 1994a171;NSString;94c18dd3;MulleObjCOutputStream
      { @selector( NSString), @selector( MulleObjCUnicode) },      // 1994a171;NSString;4d57c73a;MulleObjCUnicode
      { @selector( NSString), @selector( NSCharacterSet) },      // 1994a171;NSString;bb258d72;NSCharacterSet
      { @selector( NSString), @selector( NSCoder) },      // 1994a171;NSString;100c54ba;NSCoder
      { @selector( NSString), @selector( NSData) },      // 1994a171;NSString;8fce7861;NSData
      { @selector( NSString), @selector( NSDataPrivate) },      // 1994a171;NSString;542e5a5f;NSDataPrivate
      { @selector( NSString), @selector( NSMutableString) },      // 1994a171;NSString;63662493;NSMutableString
      { @selector( NSString), @selector( NSPropertyListParsing) },      // 1994a171;NSString;060a8c9c;NSPropertyListParsing
      { @selector( NSString), @selector( PropertyList) },      // 1994a171;NSString;827edd0f;PropertyList
      { @selector( NSString), @selector( PropertyListPrinting) },      // 1994a171;NSString;91aeee11;PropertyListPrinting
      { @selector( NSString), @selector( Regex) },      // 1994a171;NSString;0ba82189;Regex
      { @selector( NSString), @selector( Search) },      // 1994a171;NSString;646a2c9c;Search
      { @selector( NSString), @selector( Sprintf) },      // 1994a171;NSString;8d371e94;Sprintf
      { @selector( NSString), MULLE_OBJC_NO_CATEGORYID },      // 1994a171;NSString;;
      { @selector( NSThread), @selector( NSDate) },      // c81b9c22;NSThread;cfcedd21;NSDate
      { @selector( NSThread), @selector( NSDictionary) },      // c81b9c22;NSThread;8b2abcad;NSDictionary
      { @selector( NSThread), @selector( NSNotification) },      // c81b9c22;NSThread;4cf6fadb;NSNotification
      { @selector( NSThread), @selector( NSString) },      // c81b9c22;NSThread;1994a171;NSString
      { @selector( NSTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 190d1ade;NSTimeZone;;
      { @selector( NSTimer), @selector( NSDate) },      // 37c6e578;NSTimer;cfcedd21;NSDate
      { @selector( NSTimer), MULLE_OBJC_NO_CATEGORYID },      // 37c6e578;NSTimer;;
      { @selector( NSUUID), MULLE_OBJC_NO_CATEGORYID },      // 9f15f591;NSUUID;;
      { @selector( NSUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b47ff54;NSUnarchiver;;
      { @selector( NSUndoManager), MULLE_OBJC_NO_CATEGORYID },      // 0e5330bc;NSUndoManager;;
      { @selector( NSValue), @selector( NSCoder) },      // 96deaa7d;NSValue;100c54ba;NSCoder
      { @selector( NSValue), @selector( NSString) },      // 96deaa7d;NSValue;1994a171;NSString
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // 96deaa7d;NSValue;;
      { @selector( _MulleGMTTimeZone), MULLE_OBJC_NO_CATEGORYID },      // d6f534a3;_MulleGMTTimeZone;;
      { @selector( _MulleObjCASCIIString), @selector( Components) },      // b82142dd;_MulleObjCASCIIString;c6c03895;Components
      { @selector( _MulleObjCASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b82142dd;_MulleObjCASCIIString;;
      { @selector( _MulleObjCAllocatorASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b8b17987;_MulleObjCAllocatorASCIIString;;
      { @selector( _MulleObjCAllocatorData), MULLE_OBJC_NO_CATEGORYID },      // 888d9e62;_MulleObjCAllocatorData;;
      { @selector( _MulleObjCAllocatorUTF16String), MULLE_OBJC_NO_CATEGORYID },      // fadd0998;_MulleObjCAllocatorUTF16String;;
      { @selector( _MulleObjCAllocatorUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 22d56278;_MulleObjCAllocatorUTF32String;;
      { @selector( _MulleObjCAllocatorZeroTerminatedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a747ff17;_MulleObjCAllocatorZeroTerminatedASCIIString;;
      { @selector( _MulleObjCArrayEnumerator), MULLE_OBJC_NO_CATEGORYID },      // b826ca4d;_MulleObjCArrayEnumerator;;
      { @selector( _MulleObjCBoolNumber), @selector( NSString) },      // 263c5445;_MulleObjCBoolNumber;1994a171;NSString
      { @selector( _MulleObjCBoolNumber), @selector( PropertyListPrinting) },      // 263c5445;_MulleObjCBoolNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCBoolNumber), MULLE_OBJC_NO_CATEGORYID },      // 263c5445;_MulleObjCBoolNumber;;
      { @selector( _MulleObjCCheatingASCIICharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 32889ba3;_MulleObjCCheatingASCIICharacterSet;;
      { @selector( _MulleObjCCheatingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // c16079ee;_MulleObjCCheatingASCIIString;;
      { @selector( _MulleObjCConcreteArray), @selector( NSCoder) },      // 3610e4bd;_MulleObjCConcreteArray;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteArray), MULLE_OBJC_NO_CATEGORYID },      // 3610e4bd;_MulleObjCConcreteArray;;
      { @selector( _MulleObjCConcreteBitmapCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 0846adc2;_MulleObjCConcreteBitmapCharacterSet;;
      { @selector( _MulleObjCConcreteCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // a2be208e;_MulleObjCConcreteCalendarDate;;
      { @selector( _MulleObjCConcreteCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // ba1004b2;_MulleObjCConcreteCharacterSet;;
      { @selector( _MulleObjCConcreteData), MULLE_OBJC_NO_CATEGORYID },      // 9971ffa3;_MulleObjCConcreteData;;
      { @selector( _MulleObjCConcreteDate), MULLE_OBJC_NO_CATEGORYID },      // 59719ae3;_MulleObjCConcreteDate;;
      { @selector( _MulleObjCConcreteDictionary), MULLE_OBJC_NO_CATEGORYID },      // aa37b8ec;_MulleObjCConcreteDictionary;;
      { @selector( _MulleObjCConcreteInvertedCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 91ba9925;_MulleObjCConcreteInvertedCharacterSet;;
      { @selector( _MulleObjCConcreteMutableData), MULLE_OBJC_NO_CATEGORYID },      // 55d549c0;_MulleObjCConcreteMutableData;;
      { @selector( _MulleObjCConcreteMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2ce9638f;_MulleObjCConcreteMutableDictionary;;
      { @selector( _MulleObjCConcreteMutableSet), MULLE_OBJC_NO_CATEGORYID },      // b7eb37c0;_MulleObjCConcreteMutableSet;;
      { @selector( _MulleObjCConcreteRangeCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 09c86c6e;_MulleObjCConcreteRangeCharacterSet;;
      { @selector( _MulleObjCConcreteSet), MULLE_OBJC_NO_CATEGORYID },      // 2823d0a0;_MulleObjCConcreteSet;;
      { @selector( _MulleObjCConcreteValue), @selector( NSCoder) },      // 7aa5a738;_MulleObjCConcreteValue;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // 7aa5a738;_MulleObjCConcreteValue;;
      { @selector( _MulleObjCDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2b722f90;_MulleObjCDictionary;;
      { @selector( _MulleObjCDictionaryKeyEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 047702a5;_MulleObjCDictionaryKeyEnumerator;;
      { @selector( _MulleObjCDictionaryObjectEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 49965c09;_MulleObjCDictionaryObjectEnumerator;;
      { @selector( _MulleObjCDoubleNumber), @selector( NSString) },      // ae25b758;_MulleObjCDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCDoubleNumber), @selector( PropertyListPrinting) },      // ae25b758;_MulleObjCDoubleNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // ae25b758;_MulleObjCDoubleNumber;;
      { @selector( _MulleObjCEightBytesData), MULLE_OBJC_NO_CATEGORYID },      // 7ac60bf2;_MulleObjCEightBytesData;;
      { @selector( _MulleObjCEmptyArray), MULLE_OBJC_NO_CATEGORYID },      // 7aa0d636;_MulleObjCEmptyArray;;
      { @selector( _MulleObjCEmptyDictionary), @selector( NSCoder) },      // cc5dc56a;_MulleObjCEmptyDictionary;100c54ba;NSCoder
      { @selector( _MulleObjCEmptyDictionary), MULLE_OBJC_NO_CATEGORYID },      // cc5dc56a;_MulleObjCEmptyDictionary;;
      { @selector( _MulleObjCEmptySet), @selector( NSCoder) },      // b4c55b26;_MulleObjCEmptySet;100c54ba;NSCoder
      { @selector( _MulleObjCEmptySet), MULLE_OBJC_NO_CATEGORYID },      // b4c55b26;_MulleObjCEmptySet;;
      { @selector( _MulleObjCFloatNumber), @selector( NSString) },      // 0efef7c5;_MulleObjCFloatNumber;1994a171;NSString
      { @selector( _MulleObjCFloatNumber), MULLE_OBJC_NO_CATEGORYID },      // 0efef7c5;_MulleObjCFloatNumber;;
      { @selector( _MulleObjCGenericASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 2c4a2683;_MulleObjCGenericASCIIString;;
      { @selector( _MulleObjCGenericUTF16String), MULLE_OBJC_NO_CATEGORYID },      // ceb45c9e;_MulleObjCGenericUTF16String;;
      { @selector( _MulleObjCGenericUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 57fe0d78;_MulleObjCGenericUTF32String;;
      { @selector( _MulleObjCInt32Number), @selector( NSString) },      // d69971a0;_MulleObjCInt32Number;1994a171;NSString
      { @selector( _MulleObjCInt32Number), MULLE_OBJC_NO_CATEGORYID },      // d69971a0;_MulleObjCInt32Number;;
      { @selector( _MulleObjCInt64Number), @selector( NSString) },      // 8b4d5e19;_MulleObjCInt64Number;1994a171;NSString
      { @selector( _MulleObjCInt64Number), MULLE_OBJC_NO_CATEGORYID },      // 8b4d5e19;_MulleObjCInt64Number;;
      { @selector( _MulleObjCLocalTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 5813d6fc;_MulleObjCLocalTimeZone;;
      { @selector( _MulleObjCLongDoubleNumber), @selector( NSString) },      // 4ec38072;_MulleObjCLongDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCLongDoubleNumber), @selector( PropertyListPrinting) },      // 4ec38072;_MulleObjCLongDoubleNumber;91aeee11;PropertyListPrinting
      { @selector( _MulleObjCLongDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 4ec38072;_MulleObjCLongDoubleNumber;;
      { @selector( _MulleObjCMediumData), MULLE_OBJC_NO_CATEGORYID },      // bcd94429;_MulleObjCMediumData;;
      { @selector( _MulleObjCPropertyListReader), MULLE_OBJC_NO_CATEGORYID },      // a2dc8d79;_MulleObjCPropertyListReader;;
      { @selector( _MulleObjCReferencingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b6861455;_MulleObjCReferencingASCIIString;;
      { @selector( _MulleObjCSet), MULLE_OBJC_NO_CATEGORYID },      // 5da537fa;_MulleObjCSet;;
      { @selector( _MulleObjCSetEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 832b431a;_MulleObjCSetEnumerator;;
      { @selector( _MulleObjCSharedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a4a89e62;_MulleObjCSharedASCIIString;;
      { @selector( _MulleObjCSharedData), MULLE_OBJC_NO_CATEGORYID },      // 71db1e02;_MulleObjCSharedData;;
      { @selector( _MulleObjCSharedUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 06c03572;_MulleObjCSharedUTF16String;;
      { @selector( _MulleObjCSharedUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 6762de13;_MulleObjCSharedUTF32String;;
      { @selector( _MulleObjCSixteenBytesData), MULLE_OBJC_NO_CATEGORYID },      // 4b47402e;_MulleObjCSixteenBytesData;;
      { @selector( _MulleObjCTaggedPointerChar5String), @selector( Components) },      // 2a6d1009;_MulleObjCTaggedPointerChar5String;c6c03895;Components
      { @selector( _MulleObjCTaggedPointerChar5String), MULLE_OBJC_NO_CATEGORYID },      // 2a6d1009;_MulleObjCTaggedPointerChar5String;;
      { @selector( _MulleObjCTaggedPointerChar7String), @selector( Components) },      // d68ecb24;_MulleObjCTaggedPointerChar7String;c6c03895;Components
      { @selector( _MulleObjCTaggedPointerChar7String), MULLE_OBJC_NO_CATEGORYID },      // d68ecb24;_MulleObjCTaggedPointerChar7String;;
      { @selector( _MulleObjCTaggedPointerDoubleNumber), @selector( NSCoder) },      // 332cd0a3;_MulleObjCTaggedPointerDoubleNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 332cd0a3;_MulleObjCTaggedPointerDoubleNumber;;
      { @selector( _MulleObjCTaggedPointerFloatNumber), @selector( NSCoder) },      // 4ec9e1de;_MulleObjCTaggedPointerFloatNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerFloatNumber), MULLE_OBJC_NO_CATEGORYID },      // 4ec9e1de;_MulleObjCTaggedPointerFloatNumber;;
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSCoder) },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSString) },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;1994a171;NSString
      { @selector( _MulleObjCTaggedPointerIntegerNumber), MULLE_OBJC_NO_CATEGORYID },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;;
      { @selector( _MulleObjCTinyASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a20ee3f6;_MulleObjCTinyASCIIString;;
      { @selector( _MulleObjCTinyData), MULLE_OBJC_NO_CATEGORYID },      // ed2fbb7a;_MulleObjCTinyData;;
      { @selector( _MulleObjCUInt32Number), @selector( NSString) },      // 92030c9c;_MulleObjCUInt32Number;1994a171;NSString
      { @selector( _MulleObjCUInt32Number), MULLE_OBJC_NO_CATEGORYID },      // 92030c9c;_MulleObjCUInt32Number;;
      { @selector( _MulleObjCUInt64Number), @selector( NSString) },      // c62e3ae1;_MulleObjCUInt64Number;1994a171;NSString
      { @selector( _MulleObjCUInt64Number), MULLE_OBJC_NO_CATEGORYID },      // c62e3ae1;_MulleObjCUInt64Number;;
      { @selector( _MulleObjCUTF16String), @selector( Components) },      // d817650f;_MulleObjCUTF16String;c6c03895;Components
      { @selector( _MulleObjCUTF16String), @selector( Search) },      // d817650f;_MulleObjCUTF16String;646a2c9c;Search
      { @selector( _MulleObjCUTF16String), MULLE_OBJC_NO_CATEGORYID },      // d817650f;_MulleObjCUTF16String;;
      { @selector( _MulleObjCUTF32String), @selector( Components) },      // 318d8f60;_MulleObjCUTF32String;c6c03895;Components
      { @selector( _MulleObjCUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 318d8f60;_MulleObjCUTF32String;;
      { @selector( _MulleObjCZeroBytesData), MULLE_OBJC_NO_CATEGORYID },      // e3b0c32a;_MulleObjCZeroBytesData;;
      { @selector( _NSArrayPlaceholder), @selector( NSCoder) },      // 43057f70;_NSArrayPlaceholder;100c54ba;NSCoder
      { @selector( _NSArrayPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 43057f70;_NSArrayPlaceholder;;
      { @selector( _NSDictionaryPlaceholder), @selector( NSCoder) },      // 28e52164;_NSDictionaryPlaceholder;100c54ba;NSCoder
      { @selector( _NSDictionaryPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 28e52164;_NSDictionaryPlaceholder;;
      { @selector( _NSMutableDictionaryPlaceholder), @selector( NSCoder) },      // 74c8de28;_NSMutableDictionaryPlaceholder;100c54ba;NSCoder
      { @selector( _NSMutableDictionaryPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 74c8de28;_NSMutableDictionaryPlaceholder;;
      { @selector( _NSMutableSetPlaceholder), @selector( NSCoder) },      // f133938c;_NSMutableSetPlaceholder;100c54ba;NSCoder
      { @selector( _NSMutableSetPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // f133938c;_NSMutableSetPlaceholder;;
      { @selector( _NSSetPlaceholder), @selector( NSCoder) },      // 5929a24b;_NSSetPlaceholder;100c54ba;NSCoder
      { @selector( _NSSetPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 5929a24b;_NSSetPlaceholder;;
